DB_USERNAME=root
DB_PASSWORD=root@123

GOOGLE_CLIENT_ID=your_real_google_client_id
GOOGLE_CLIENT_SECRET=your_real_google_client_secret

JWT_SECRET=BookVerseSecretKeyForJWTAuthentication2026SecureKey12345